CREATE TABLE maquina (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    tipo ENUM('CARDIO', 'MUSCULACAO', 'FUNCIONAL', 'OUTRO') NOT NULL,
    marca VARCHAR(80) NULL,
    modelo VARCHAR(80) NULL,
    codigo_patrimonio VARCHAR(50) NULL,
    localizacao VARCHAR(120) NULL,
    status ENUM('ATIVA', 'MANUTENCAO', 'INATIVA') NOT NULL DEFAULT 'ATIVA',
    observacoes VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_maquina_codigo_patrimonio UNIQUE (codigo_patrimonio)
);
